/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_az_inscription (void);
GtkWidget* create_az_connexion (void);
GtkWidget* create_az_admin (void);
GtkWidget* create_adminajout (void);
GtkWidget* create_az_supression (void);
GtkWidget* create_az_modif (void);
GtkWidget* create_ad_modif (void);
GtkWidget* create_adminaffiche (void);
GtkWidget* create_affichage_niveau (void);
