/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_MA_Interface_Acceuil (void)
{
  GtkWidget *MA_Interface_Acceuil;
  GtkWidget *MA_fixed1;
  GtkWidget *MA_button_Modifier_acceuil;
  GtkWidget *MA_alignment_modifier_acceuil;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label10;
  GtkWidget *MA_button_Supprimer_acceuil;
  GtkWidget *MA_alignment_supprimer_acceuil;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label11;
  GtkWidget *MA_treeview_LS_acceuil;
  GtkWidget *MA_label_LS_acceuil;
  GtkWidget *MA_button_Ajouter_acceuil;
  GtkWidget *MA_alignment_ajouter_acceuil;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label9;
  GtkWidget *MA_button_recherche_acceuil;
  GtkWidget *MA_alignment_recherche_acceuil;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label15;
  GtkWidget *MA_button_actualiser_acceuil;
  GtkWidget *alignment20;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label62;
  GtkWidget *MA_button_rps_acceuil;
  GtkWidget *alignment21;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label63;

  MA_Interface_Acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MA_Interface_Acceuil), _("Acceuil"));

  MA_fixed1 = gtk_fixed_new ();
  gtk_widget_show (MA_fixed1);
  gtk_container_add (GTK_CONTAINER (MA_Interface_Acceuil), MA_fixed1);

  MA_button_Modifier_acceuil = gtk_button_new ();
  gtk_widget_show (MA_button_Modifier_acceuil);
  gtk_fixed_put (GTK_FIXED (MA_fixed1), MA_button_Modifier_acceuil, 776, 728);
  gtk_widget_set_size_request (MA_button_Modifier_acceuil, 272, 64);

  MA_alignment_modifier_acceuil = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (MA_alignment_modifier_acceuil);
  gtk_container_add (GTK_CONTAINER (MA_button_Modifier_acceuil), MA_alignment_modifier_acceuil);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (MA_alignment_modifier_acceuil), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox2), label10, FALSE, FALSE, 0);

  MA_button_Supprimer_acceuil = gtk_button_new ();
  gtk_widget_show (MA_button_Supprimer_acceuil);
  gtk_fixed_put (GTK_FIXED (MA_fixed1), MA_button_Supprimer_acceuil, 1208, 728);
  gtk_widget_set_size_request (MA_button_Supprimer_acceuil, 272, 64);

  MA_alignment_supprimer_acceuil = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (MA_alignment_supprimer_acceuil);
  gtk_container_add (GTK_CONTAINER (MA_button_Supprimer_acceuil), MA_alignment_supprimer_acceuil);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (MA_alignment_supprimer_acceuil), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, FALSE, FALSE, 0);

  MA_treeview_LS_acceuil = gtk_tree_view_new ();
  gtk_widget_show (MA_treeview_LS_acceuil);
  gtk_fixed_put (GTK_FIXED (MA_fixed1), MA_treeview_LS_acceuil, 616, 280);
  gtk_widget_set_size_request (MA_treeview_LS_acceuil, 584, 272);

  MA_label_LS_acceuil = gtk_label_new (_("Liste du Stock"));
  gtk_widget_show (MA_label_LS_acceuil);
  gtk_fixed_put (GTK_FIXED (MA_fixed1), MA_label_LS_acceuil, 784, 208);
  gtk_widget_set_size_request (MA_label_LS_acceuil, 240, 64);

  MA_button_Ajouter_acceuil = gtk_button_new ();
  gtk_widget_show (MA_button_Ajouter_acceuil);
  gtk_fixed_put (GTK_FIXED (MA_fixed1), MA_button_Ajouter_acceuil, 360, 728);
  gtk_widget_set_size_request (MA_button_Ajouter_acceuil, 272, 64);

  MA_alignment_ajouter_acceuil = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (MA_alignment_ajouter_acceuil);
  gtk_container_add (GTK_CONTAINER (MA_button_Ajouter_acceuil), MA_alignment_ajouter_acceuil);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (MA_alignment_ajouter_acceuil), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox1), label9, FALSE, FALSE, 0);

  MA_button_recherche_acceuil = gtk_button_new ();
  gtk_widget_show (MA_button_recherche_acceuil);
  gtk_fixed_put (GTK_FIXED (MA_fixed1), MA_button_recherche_acceuil, 1440, 80);
  gtk_widget_set_size_request (MA_button_recherche_acceuil, 272, 53);

  MA_alignment_recherche_acceuil = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (MA_alignment_recherche_acceuil);
  gtk_container_add (GTK_CONTAINER (MA_button_recherche_acceuil), MA_alignment_recherche_acceuil);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (MA_alignment_recherche_acceuil), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox6), label15, FALSE, FALSE, 0);

  MA_button_actualiser_acceuil = gtk_button_new ();
  gtk_widget_show (MA_button_actualiser_acceuil);
  gtk_fixed_put (GTK_FIXED (MA_fixed1), MA_button_actualiser_acceuil, 1104, 568);
  gtk_widget_set_size_request (MA_button_actualiser_acceuil, 96, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (MA_button_actualiser_acceuil), alignment20);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox16), label62, FALSE, FALSE, 0);

  MA_button_rps_acceuil = gtk_button_new ();
  gtk_widget_show (MA_button_rps_acceuil);
  gtk_fixed_put (GTK_FIXED (MA_fixed1), MA_button_rps_acceuil, 250, 80);
  gtk_widget_set_size_request (MA_button_rps_acceuil, 272, 53);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (MA_button_rps_acceuil), alignment21);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("Rupture de stock"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox17), label63, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) MA_button_Modifier_acceuil, "clicked",
                    G_CALLBACK (on_MA_button_Modifier_acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_button_Supprimer_acceuil, "clicked",
                    G_CALLBACK (on_MA_button_Supprimer_acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_treeview_LS_acceuil, "row_activated",
                    G_CALLBACK (on_MA_treeview_LS_acceuil_row_activated),
                    NULL);
  g_signal_connect ((gpointer) MA_button_Ajouter_acceuil, "clicked",
                    G_CALLBACK (on_MA_button_Ajouter_acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_button_recherche_acceuil, "clicked",
                    G_CALLBACK (on_MA_button_recherche_acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_button_actualiser_acceuil, "clicked",
                    G_CALLBACK (on_MA_button_actualiser_acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_button_rps_acceuil, "clicked",
                    G_CALLBACK (on_MA_button_rps_acceuil_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MA_Interface_Acceuil, MA_Interface_Acceuil, "MA_Interface_Acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_fixed1, "MA_fixed1");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_button_Modifier_acceuil, "MA_button_Modifier_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_alignment_modifier_acceuil, "MA_alignment_modifier_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, image2, "image2");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, label10, "label10");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_button_Supprimer_acceuil, "MA_button_Supprimer_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_alignment_supprimer_acceuil, "MA_alignment_supprimer_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, image3, "image3");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, label11, "label11");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_treeview_LS_acceuil, "MA_treeview_LS_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_label_LS_acceuil, "MA_label_LS_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_button_Ajouter_acceuil, "MA_button_Ajouter_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_alignment_ajouter_acceuil, "MA_alignment_ajouter_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, image1, "image1");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, label9, "label9");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_button_recherche_acceuil, "MA_button_recherche_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_alignment_recherche_acceuil, "MA_alignment_recherche_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, image6, "image6");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, label15, "label15");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_button_actualiser_acceuil, "MA_button_actualiser_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, image16, "image16");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, label62, "label62");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, MA_button_rps_acceuil, "MA_button_rps_acceuil");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, image17, "image17");
  GLADE_HOOKUP_OBJECT (MA_Interface_Acceuil, label63, "label63");

  return MA_Interface_Acceuil;
}

GtkWidget*
create_MA_Interface_Ajouter (void)
{
  GtkWidget *MA_Interface_Ajouter;
  GtkWidget *MA_fixed3;
  GtkWidget *MA_entry_nomproduit_ajouter;
  GtkWidget *MA_label_nomproduit_ajouter;
  GtkWidget *MA_entry_ref_ajouter;
  GtkWidget *MA_label_ddp_ajouter;
  GtkWidget *MA_entry_qte_ajouter;
  GtkWidget *MA_label_ref_ajouter;
  GtkWidget *MA_alignment_cat_ajouter;
  GtkWidget *MA_comboboxentry_cat_ajouter;
  GtkWidget *MA_button_acceuil_ajouter;
  GtkWidget *alignment5;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label13;
  GtkWidget *MA_button_confirmer_ajouter;
  GtkWidget *alignment6;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label14;
  GtkWidget *MA_label_cat_ajouter;
  GtkWidget *MA_label_qte_ajouter;
  GtkObject *MA_spinbutton_dpj_ajouter_adj;
  GtkWidget *MA_spinbutton_dpj_ajouter;
  GtkObject *MA_spinbutton_dpm_ajouter_adj;
  GtkWidget *MA_spinbutton_dpm_ajouter;
  GtkObject *MA_spinbutton_dpa_ajouter_adj;
  GtkWidget *MA_spinbutton_dpa_ajouter;
  GtkWidget *MA_label_annee_ajouter;
  GtkWidget *MA_label_mois_ajouter;
  GtkWidget *MA_label_jour_ajouter;
  GtkWidget *MA_label_stockage_ajouter;
  GtkWidget *MA_radiobutton_congele_ajouter;
  GSList *MA_radiobutton_congele_ajouter_group = NULL;
  GtkWidget *MA_radiobutton_refrigere_ajouter;
  GtkWidget *MA_radiobutton_TA_ajouter;

  MA_Interface_Ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MA_Interface_Ajouter), _("Ajouter"));

  MA_fixed3 = gtk_fixed_new ();
  gtk_widget_show (MA_fixed3);
  gtk_container_add (GTK_CONTAINER (MA_Interface_Ajouter), MA_fixed3);

  MA_entry_nomproduit_ajouter = gtk_entry_new ();
  gtk_widget_show (MA_entry_nomproduit_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_entry_nomproduit_ajouter, 850, 150);
  gtk_widget_set_size_request (MA_entry_nomproduit_ajouter, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (MA_entry_nomproduit_ajouter), 8226);

  MA_label_nomproduit_ajouter = gtk_label_new (_("Nom Du  Produit"));
  gtk_widget_show (MA_label_nomproduit_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_label_nomproduit_ajouter, 500, 150);
  gtk_widget_set_size_request (MA_label_nomproduit_ajouter, 160, 30);

  MA_entry_ref_ajouter = gtk_entry_new ();
  gtk_widget_show (MA_entry_ref_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_entry_ref_ajouter, 850, 100);
  gtk_widget_set_size_request (MA_entry_ref_ajouter, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (MA_entry_ref_ajouter), 8226);

  MA_label_ddp_ajouter = gtk_label_new (_("Date de p\303\251remption"));
  gtk_widget_show (MA_label_ddp_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_label_ddp_ajouter, 500, 250);
  gtk_widget_set_size_request (MA_label_ddp_ajouter, 160, 30);

  MA_entry_qte_ajouter = gtk_entry_new ();
  gtk_widget_show (MA_entry_qte_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_entry_qte_ajouter, 850, 350);
  gtk_widget_set_size_request (MA_entry_qte_ajouter, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (MA_entry_qte_ajouter), 8226);

  MA_label_ref_ajouter = gtk_label_new (_("R\303\251f"));
  gtk_widget_show (MA_label_ref_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_label_ref_ajouter, 500, 100);
  gtk_widget_set_size_request (MA_label_ref_ajouter, 160, 30);

  MA_alignment_cat_ajouter = gtk_alignment_new (0.5, 0.5, 1, 0.99);
  gtk_widget_show (MA_alignment_cat_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_alignment_cat_ajouter, 850, 450);
  gtk_widget_set_size_request (MA_alignment_cat_ajouter, 189, 29);

  MA_comboboxentry_cat_ajouter = gtk_combo_box_entry_new_text ();
  gtk_widget_show (MA_comboboxentry_cat_ajouter);
  gtk_container_add (GTK_CONTAINER (MA_alignment_cat_ajouter), MA_comboboxentry_cat_ajouter);
  gtk_widget_set_size_request (MA_comboboxentry_cat_ajouter, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (MA_comboboxentry_cat_ajouter), _("Fruit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MA_comboboxentry_cat_ajouter), _("l\303\251gumes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MA_comboboxentry_cat_ajouter), _("Boissons"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MA_comboboxentry_cat_ajouter), _("autres"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MA_comboboxentry_cat_ajouter), "");

  MA_button_acceuil_ajouter = gtk_button_new ();
  gtk_widget_show (MA_button_acceuil_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_button_acceuil_ajouter, 400, 700);
  gtk_widget_set_size_request (MA_button_acceuil_ajouter, 300, 100);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (MA_button_acceuil_ajouter), alignment5);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox4), label13, FALSE, FALSE, 0);

  MA_button_confirmer_ajouter = gtk_button_new ();
  gtk_widget_show (MA_button_confirmer_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_button_confirmer_ajouter, 1000, 700);
  gtk_widget_set_size_request (MA_button_confirmer_ajouter, 300, 100);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (MA_button_confirmer_ajouter), alignment6);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox5), label14, FALSE, FALSE, 0);

  MA_label_cat_ajouter = gtk_label_new (_("Cat\303\251gorie"));
  gtk_widget_show (MA_label_cat_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_label_cat_ajouter, 500, 450);
  gtk_widget_set_size_request (MA_label_cat_ajouter, 120, 25);

  MA_label_qte_ajouter = gtk_label_new (_("Quantit\303\251 \303\240 ajouter"));
  gtk_widget_show (MA_label_qte_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_label_qte_ajouter, 500, 350);
  gtk_widget_set_size_request (MA_label_qte_ajouter, 160, 30);

  MA_spinbutton_dpj_ajouter_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  MA_spinbutton_dpj_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (MA_spinbutton_dpj_ajouter_adj), 1, 0);
  gtk_widget_show (MA_spinbutton_dpj_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_spinbutton_dpj_ajouter, 850, 250);
  gtk_widget_set_size_request (MA_spinbutton_dpj_ajouter, 60, 27);

  MA_spinbutton_dpm_ajouter_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  MA_spinbutton_dpm_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (MA_spinbutton_dpm_ajouter_adj), 1, 0);
  gtk_widget_show (MA_spinbutton_dpm_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_spinbutton_dpm_ajouter, 1000, 250);
  gtk_widget_set_size_request (MA_spinbutton_dpm_ajouter, 60, 27);

  MA_spinbutton_dpa_ajouter_adj = gtk_adjustment_new (2021, 2021, 2031, 1, 10, 10);
  MA_spinbutton_dpa_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (MA_spinbutton_dpa_ajouter_adj), 1, 0);
  gtk_widget_show (MA_spinbutton_dpa_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_spinbutton_dpa_ajouter, 1150, 250);
  gtk_widget_set_size_request (MA_spinbutton_dpa_ajouter, 60, 27);

  MA_label_annee_ajouter = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (MA_label_annee_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_label_annee_ajouter, 1150, 210);
  gtk_widget_set_size_request (MA_label_annee_ajouter, 41, 17);

  MA_label_mois_ajouter = gtk_label_new (_("mois"));
  gtk_widget_show (MA_label_mois_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_label_mois_ajouter, 1000, 210);
  gtk_widget_set_size_request (MA_label_mois_ajouter, 41, 17);

  MA_label_jour_ajouter = gtk_label_new (_("jour"));
  gtk_widget_show (MA_label_jour_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_label_jour_ajouter, 850, 210);
  gtk_widget_set_size_request (MA_label_jour_ajouter, 41, 17);

  MA_label_stockage_ajouter = gtk_label_new (_("Stockage"));
  gtk_widget_show (MA_label_stockage_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_label_stockage_ajouter, 500, 550);
  gtk_widget_set_size_request (MA_label_stockage_ajouter, 160, 30);

  MA_radiobutton_congele_ajouter = gtk_radio_button_new_with_mnemonic (NULL, _("Congel\303\251"));
  gtk_widget_show (MA_radiobutton_congele_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_radiobutton_congele_ajouter, 840, 552);
  gtk_widget_set_size_request (MA_radiobutton_congele_ajouter, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (MA_radiobutton_congele_ajouter), MA_radiobutton_congele_ajouter_group);
  MA_radiobutton_congele_ajouter_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (MA_radiobutton_congele_ajouter));

  MA_radiobutton_refrigere_ajouter = gtk_radio_button_new_with_mnemonic (NULL, _("R\303\251frig\303\251r\303\251"));
  gtk_widget_show (MA_radiobutton_refrigere_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_radiobutton_refrigere_ajouter, 1032, 552);
  gtk_widget_set_size_request (MA_radiobutton_refrigere_ajouter, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (MA_radiobutton_refrigere_ajouter), MA_radiobutton_congele_ajouter_group);
  MA_radiobutton_congele_ajouter_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (MA_radiobutton_refrigere_ajouter));

  MA_radiobutton_TA_ajouter = gtk_radio_button_new_with_mnemonic (NULL, _("Temperature ambiante"));
  gtk_widget_show (MA_radiobutton_TA_ajouter);
  gtk_fixed_put (GTK_FIXED (MA_fixed3), MA_radiobutton_TA_ajouter, 1232, 552);
  gtk_widget_set_size_request (MA_radiobutton_TA_ajouter, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (MA_radiobutton_TA_ajouter), MA_radiobutton_congele_ajouter_group);
  MA_radiobutton_congele_ajouter_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (MA_radiobutton_TA_ajouter));

  g_signal_connect ((gpointer) MA_button_acceuil_ajouter, "clicked",
                    G_CALLBACK (on_MA_button_acceuil_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_button_confirmer_ajouter, "clicked",
                    G_CALLBACK (on_MA_button_confirmer_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_radiobutton_congele_ajouter, "toggled",
                    G_CALLBACK (on_MA_radiobutton_congele_ajouter_toggled),
                    NULL);
  g_signal_connect ((gpointer) MA_radiobutton_refrigere_ajouter, "toggled",
                    G_CALLBACK (on_MA_radiobutton_refrigere_ajouter_toggled),
                    NULL);
  g_signal_connect ((gpointer) MA_radiobutton_TA_ajouter, "toggled",
                    G_CALLBACK (on_MA_radiobutton_TA_ajouter_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MA_Interface_Ajouter, MA_Interface_Ajouter, "MA_Interface_Ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_fixed3, "MA_fixed3");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_entry_nomproduit_ajouter, "MA_entry_nomproduit_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_label_nomproduit_ajouter, "MA_label_nomproduit_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_entry_ref_ajouter, "MA_entry_ref_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_label_ddp_ajouter, "MA_label_ddp_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_entry_qte_ajouter, "MA_entry_qte_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_label_ref_ajouter, "MA_label_ref_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_alignment_cat_ajouter, "MA_alignment_cat_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_comboboxentry_cat_ajouter, "MA_comboboxentry_cat_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_button_acceuil_ajouter, "MA_button_acceuil_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, image4, "image4");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, label13, "label13");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_button_confirmer_ajouter, "MA_button_confirmer_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, image5, "image5");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, label14, "label14");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_label_cat_ajouter, "MA_label_cat_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_label_qte_ajouter, "MA_label_qte_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_spinbutton_dpj_ajouter, "MA_spinbutton_dpj_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_spinbutton_dpm_ajouter, "MA_spinbutton_dpm_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_spinbutton_dpa_ajouter, "MA_spinbutton_dpa_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_label_annee_ajouter, "MA_label_annee_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_label_mois_ajouter, "MA_label_mois_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_label_jour_ajouter, "MA_label_jour_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_label_stockage_ajouter, "MA_label_stockage_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_radiobutton_congele_ajouter, "MA_radiobutton_congele_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_radiobutton_refrigere_ajouter, "MA_radiobutton_refrigere_ajouter");
  GLADE_HOOKUP_OBJECT (MA_Interface_Ajouter, MA_radiobutton_TA_ajouter, "MA_radiobutton_TA_ajouter");

  return MA_Interface_Ajouter;
}

GtkWidget*
create_MA_Interface_Supprimer (void)
{
  GtkWidget *MA_Interface_Supprimer;
  GtkWidget *MA_fixed2;
  GtkWidget *MA_label_ref_supprimer;
  GtkWidget *MA_entry_ref_supprimer;
  GtkWidget *MA_button_supprimer_supprimer;
  GtkWidget *alignment8;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label18;
  GtkWidget *MA_button_acceuil_supprimer;
  GtkWidget *alignment9;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label19;
  GtkWidget *MA_checkbutton_confirmer_supprimer;

  MA_Interface_Supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MA_Interface_Supprimer), _("Supprimer"));

  MA_fixed2 = gtk_fixed_new ();
  gtk_widget_show (MA_fixed2);
  gtk_container_add (GTK_CONTAINER (MA_Interface_Supprimer), MA_fixed2);

  MA_label_ref_supprimer = gtk_label_new (_("R\303\251f\303\251rence Produit"));
  gtk_widget_show (MA_label_ref_supprimer);
  gtk_fixed_put (GTK_FIXED (MA_fixed2), MA_label_ref_supprimer, 648, 296);
  gtk_widget_set_size_request (MA_label_ref_supprimer, 184, 33);

  MA_entry_ref_supprimer = gtk_entry_new ();
  gtk_widget_show (MA_entry_ref_supprimer);
  gtk_fixed_put (GTK_FIXED (MA_fixed2), MA_entry_ref_supprimer, 928, 296);
  gtk_widget_set_size_request (MA_entry_ref_supprimer, 168, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (MA_entry_ref_supprimer), 8226);

  MA_button_supprimer_supprimer = gtk_button_new ();
  gtk_widget_show (MA_button_supprimer_supprimer);
  gtk_fixed_put (GTK_FIXED (MA_fixed2), MA_button_supprimer_supprimer, 800, 432);
  gtk_widget_set_size_request (MA_button_supprimer_supprimer, 224, 45);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (MA_button_supprimer_supprimer), alignment8);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox7), label18, FALSE, FALSE, 0);

  MA_button_acceuil_supprimer = gtk_button_new ();
  gtk_widget_show (MA_button_acceuil_supprimer);
  gtk_fixed_put (GTK_FIXED (MA_fixed2), MA_button_acceuil_supprimer, 216, 704);
  gtk_widget_set_size_request (MA_button_acceuil_supprimer, 224, 53);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (MA_button_acceuil_supprimer), alignment9);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox8), label19, FALSE, FALSE, 0);

  MA_checkbutton_confirmer_supprimer = gtk_check_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (MA_checkbutton_confirmer_supprimer);
  gtk_fixed_put (GTK_FIXED (MA_fixed2), MA_checkbutton_confirmer_supprimer, 1176, 304);
  gtk_widget_set_size_request (MA_checkbutton_confirmer_supprimer, 118, 24);

  g_signal_connect ((gpointer) MA_button_supprimer_supprimer, "clicked",
                    G_CALLBACK (on_MA_button_supprimer_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_button_acceuil_supprimer, "clicked",
                    G_CALLBACK (on_MA_button_acceuil_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_checkbutton_confirmer_supprimer, "toggled",
                    G_CALLBACK (on_MA_checkbutton_confirmer_supprimer_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MA_Interface_Supprimer, MA_Interface_Supprimer, "MA_Interface_Supprimer");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, MA_fixed2, "MA_fixed2");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, MA_label_ref_supprimer, "MA_label_ref_supprimer");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, MA_entry_ref_supprimer, "MA_entry_ref_supprimer");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, MA_button_supprimer_supprimer, "MA_button_supprimer_supprimer");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, image7, "image7");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, label18, "label18");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, MA_button_acceuil_supprimer, "MA_button_acceuil_supprimer");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, image8, "image8");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, label19, "label19");
  GLADE_HOOKUP_OBJECT (MA_Interface_Supprimer, MA_checkbutton_confirmer_supprimer, "MA_checkbutton_confirmer_supprimer");

  return MA_Interface_Supprimer;
}

GtkWidget*
create_MA_Interface_Rechercher (void)
{
  GtkWidget *MA_Interface_Rechercher;
  GtkWidget *MA_fixed4;
  GtkWidget *Ma_label_refr_chercher;
  GtkWidget *MA_entry_refr_chercher;
  GtkWidget *MA_button_rechercher_rechercher;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label21;
  GtkWidget *MA_label_nom_rechercher;
  GtkWidget *MA_label_dp_rechercher;
  GtkWidget *MA_label_nomO_rechercher;
  GtkWidget *MA_label_dpjO_rechercher;
  GtkWidget *MA_label_dpmO_rechercher;
  GtkWidget *MA_label_dpaO_rechercher;
  GtkWidget *MA_button_acceuil_rechercher;
  GtkWidget *alignment11;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label32;
  GtkWidget *MA_label_qte_rechercher;
  GtkWidget *MA_label_cat_rechercher;
  GtkWidget *MA_label_qteO_rechercher;
  GtkWidget *MA_label_catO_rechercher;
  GtkWidget *MA_label_stockage_rechercher;
  GtkWidget *MA_label_stockageO_rechercher;

  MA_Interface_Rechercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MA_Interface_Rechercher), _("Rechercher"));

  MA_fixed4 = gtk_fixed_new ();
  gtk_widget_show (MA_fixed4);
  gtk_container_add (GTK_CONTAINER (MA_Interface_Rechercher), MA_fixed4);

  Ma_label_refr_chercher = gtk_label_new (_("R\303\251f"));
  gtk_widget_show (Ma_label_refr_chercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), Ma_label_refr_chercher, 520, 88);
  gtk_widget_set_size_request (Ma_label_refr_chercher, 192, 40);

  MA_entry_refr_chercher = gtk_entry_new ();
  gtk_widget_show (MA_entry_refr_chercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_entry_refr_chercher, 816, 96);
  gtk_widget_set_size_request (MA_entry_refr_chercher, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MA_entry_refr_chercher), 8226);

  MA_button_rechercher_rechercher = gtk_button_new ();
  gtk_widget_show (MA_button_rechercher_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_button_rechercher_rechercher, 1144, 80);
  gtk_widget_set_size_request (MA_button_rechercher_rechercher, 184, 64);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (MA_button_rechercher_rechercher), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox9), label21, FALSE, FALSE, 0);

  MA_label_nom_rechercher = gtk_label_new (_("Nom"));
  gtk_widget_show (MA_label_nom_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_nom_rechercher, 600, 240);
  gtk_widget_set_size_request (MA_label_nom_rechercher, 49, 17);

  MA_label_dp_rechercher = gtk_label_new (_("Date de peremption"));
  gtk_widget_show (MA_label_dp_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_dp_rechercher, 744, 240);
  gtk_widget_set_size_request (MA_label_dp_rechercher, 152, 16);

  MA_label_nomO_rechercher = gtk_label_new ("");
  gtk_widget_show (MA_label_nomO_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_nomO_rechercher, 600, 328);
  gtk_widget_set_size_request (MA_label_nomO_rechercher, 49, 17);

  MA_label_dpjO_rechercher = gtk_label_new (_("Jour"));
  gtk_widget_show (MA_label_dpjO_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_dpjO_rechercher, 736, 328);
  gtk_widget_set_size_request (MA_label_dpjO_rechercher, 49, 17);

  MA_label_dpmO_rechercher = gtk_label_new (_("Mois"));
  gtk_widget_show (MA_label_dpmO_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_dpmO_rechercher, 800, 328);
  gtk_widget_set_size_request (MA_label_dpmO_rechercher, 49, 17);

  MA_label_dpaO_rechercher = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (MA_label_dpaO_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_dpaO_rechercher, 864, 328);
  gtk_widget_set_size_request (MA_label_dpaO_rechercher, 49, 17);

  MA_button_acceuil_rechercher = gtk_button_new ();
  gtk_widget_show (MA_button_acceuil_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_button_acceuil_rechercher, 808, 520);
  gtk_widget_set_size_request (MA_button_acceuil_rechercher, 192, 69);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (MA_button_acceuil_rechercher), alignment11);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox10), label32, FALSE, FALSE, 0);

  MA_label_qte_rechercher = gtk_label_new (_("Quantit\303\251"));
  gtk_widget_show (MA_label_qte_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_qte_rechercher, 992, 240);
  gtk_widget_set_size_request (MA_label_qte_rechercher, 72, 17);

  MA_label_cat_rechercher = gtk_label_new (_("Categorie"));
  gtk_widget_show (MA_label_cat_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_cat_rechercher, 1152, 240);
  gtk_widget_set_size_request (MA_label_cat_rechercher, 72, 16);

  MA_label_qteO_rechercher = gtk_label_new (_("Qte"));
  gtk_widget_show (MA_label_qteO_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_qteO_rechercher, 1000, 328);
  gtk_widget_set_size_request (MA_label_qteO_rechercher, 49, 17);

  MA_label_catO_rechercher = gtk_label_new (_("Cat"));
  gtk_widget_show (MA_label_catO_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_catO_rechercher, 1168, 328);
  gtk_widget_set_size_request (MA_label_catO_rechercher, 49, 17);

  MA_label_stockage_rechercher = gtk_label_new (_("Stockage"));
  gtk_widget_show (MA_label_stockage_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_stockage_rechercher, 1328, 240);
  gtk_widget_set_size_request (MA_label_stockage_rechercher, 152, 24);

  MA_label_stockageO_rechercher = gtk_label_new (_("stockage"));
  gtk_widget_show (MA_label_stockageO_rechercher);
  gtk_fixed_put (GTK_FIXED (MA_fixed4), MA_label_stockageO_rechercher, 1312, 320);
  gtk_widget_set_size_request (MA_label_stockageO_rechercher, 184, 24);

  g_signal_connect ((gpointer) MA_button_rechercher_rechercher, "clicked",
                    G_CALLBACK (on_MA_button_rechercher_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_button_acceuil_rechercher, "clicked",
                    G_CALLBACK (on_MA_button_acceuil_rechercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MA_Interface_Rechercher, MA_Interface_Rechercher, "MA_Interface_Rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_fixed4, "MA_fixed4");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, Ma_label_refr_chercher, "Ma_label_refr_chercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_entry_refr_chercher, "MA_entry_refr_chercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_button_rechercher_rechercher, "MA_button_rechercher_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, image9, "image9");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, label21, "label21");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_nom_rechercher, "MA_label_nom_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_dp_rechercher, "MA_label_dp_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_nomO_rechercher, "MA_label_nomO_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_dpjO_rechercher, "MA_label_dpjO_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_dpmO_rechercher, "MA_label_dpmO_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_dpaO_rechercher, "MA_label_dpaO_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_button_acceuil_rechercher, "MA_button_acceuil_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, image10, "image10");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, label32, "label32");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_qte_rechercher, "MA_label_qte_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_cat_rechercher, "MA_label_cat_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_qteO_rechercher, "MA_label_qteO_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_catO_rechercher, "MA_label_catO_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_stockage_rechercher, "MA_label_stockage_rechercher");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rechercher, MA_label_stockageO_rechercher, "MA_label_stockageO_rechercher");

  return MA_Interface_Rechercher;
}

GtkWidget*
create_MA_interface_modifier (void)
{
  GtkWidget *MA_interface_modifier;
  GtkWidget *MA_fixed5;
  GtkWidget *MA_entry_nom_modifier;
  GtkWidget *MA_label_nom_modifier;
  GtkWidget *MA_entry_ref_modifier;
  GtkWidget *MA_label_dp_modifier;
  GtkWidget *MA_label_dpj_modifier;
  GtkWidget *MA_label_dpm_modifier;
  GtkWidget *MA_label_dpa_modifier;
  GtkWidget *MA_entry_qte_modifier;
  GtkWidget *MA_label_qte_modifier;
  GtkWidget *MA_label_ref_modifier;
  GtkWidget *MA_alignment_cat_modifier;
  GtkWidget *MA_comboboxentry_cat_modifier;
  GtkWidget *MA_label_cat_modifier;
  GtkWidget *MA_button_acceuil_modifier;
  GtkWidget *MA_alignment_acceuil_modifier;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label60;
  GtkWidget *MA_button_modifier_modifier;
  GtkWidget *alignment19;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label61;
  GtkWidget *MA_entry_refm_modifier;
  GtkWidget *MA_label_refm_modifier;
  GtkObject *MA_spinbutton_dpj_modifier_adj;
  GtkWidget *MA_spinbutton_dpj_modifier;
  GtkObject *MA_spinbutton_dpm_modifier_adj;
  GtkWidget *MA_spinbutton_dpm_modifier;
  GtkObject *MA_spinbutton_dpa_modifier_adj;
  GtkWidget *MA_spinbutton_dpa_modifier;
  GtkWidget *MA_label_stockage_modifier;
  GtkWidget *MA_radiobutton_congele_modifier;
  GSList *MA_radiobutton_congele_modifier_group = NULL;
  GtkWidget *MA_radiobutton_refrigere_modifier;
  GtkWidget *MA_radiobutton_TA_modifier;

  MA_interface_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MA_interface_modifier), _("Modifier"));

  MA_fixed5 = gtk_fixed_new ();
  gtk_widget_show (MA_fixed5);
  gtk_container_add (GTK_CONTAINER (MA_interface_modifier), MA_fixed5);

  MA_entry_nom_modifier = gtk_entry_new ();
  gtk_widget_show (MA_entry_nom_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_entry_nom_modifier, 864, 144);
  gtk_widget_set_size_request (MA_entry_nom_modifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MA_entry_nom_modifier), 8226);

  MA_label_nom_modifier = gtk_label_new (_("Nom Du  Produit"));
  gtk_widget_show (MA_label_nom_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_label_nom_modifier, 504, 144);
  gtk_widget_set_size_request (MA_label_nom_modifier, 144, 32);

  MA_entry_ref_modifier = gtk_entry_new ();
  gtk_widget_show (MA_entry_ref_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_entry_ref_modifier, 864, 80);
  gtk_widget_set_size_request (MA_entry_ref_modifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MA_entry_ref_modifier), 8226);

  MA_label_dp_modifier = gtk_label_new (_("Date de p\303\251remption"));
  gtk_widget_show (MA_label_dp_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_label_dp_modifier, 512, 240);
  gtk_widget_set_size_request (MA_label_dp_modifier, 152, 40);

  MA_label_dpj_modifier = gtk_label_new (_("jour"));
  gtk_widget_show (MA_label_dpj_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_label_dpj_modifier, 872, 208);
  gtk_widget_set_size_request (MA_label_dpj_modifier, 41, 17);

  MA_label_dpm_modifier = gtk_label_new (_("mois"));
  gtk_widget_show (MA_label_dpm_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_label_dpm_modifier, 1000, 208);
  gtk_widget_set_size_request (MA_label_dpm_modifier, 41, 17);

  MA_label_dpa_modifier = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (MA_label_dpa_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_label_dpa_modifier, 1120, 208);
  gtk_widget_set_size_request (MA_label_dpa_modifier, 41, 17);

  MA_entry_qte_modifier = gtk_entry_new ();
  gtk_widget_show (MA_entry_qte_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_entry_qte_modifier, 864, 344);
  gtk_widget_set_size_request (MA_entry_qte_modifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MA_entry_qte_modifier), 8226);

  MA_label_qte_modifier = gtk_label_new (_("Quantit\303\251 \303\240 ajouter"));
  gtk_widget_show (MA_label_qte_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_label_qte_modifier, 488, 344);
  gtk_widget_set_size_request (MA_label_qte_modifier, 184, 32);

  MA_label_ref_modifier = gtk_label_new (_("R\303\251f"));
  gtk_widget_show (MA_label_ref_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_label_ref_modifier, 552, 80);
  gtk_widget_set_size_request (MA_label_ref_modifier, 41, 17);

  MA_alignment_cat_modifier = gtk_alignment_new (0.5, 0.5, 1, 0.99);
  gtk_widget_show (MA_alignment_cat_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_alignment_cat_modifier, 864, 416);
  gtk_widget_set_size_request (MA_alignment_cat_modifier, 189, 29);

  MA_comboboxentry_cat_modifier = gtk_combo_box_entry_new_text ();
  gtk_widget_show (MA_comboboxentry_cat_modifier);
  gtk_container_add (GTK_CONTAINER (MA_alignment_cat_modifier), MA_comboboxentry_cat_modifier);
  gtk_widget_set_size_request (MA_comboboxentry_cat_modifier, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (MA_comboboxentry_cat_modifier), _("Fruit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MA_comboboxentry_cat_modifier), _("l\303\251gumes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MA_comboboxentry_cat_modifier), _("Boissons"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MA_comboboxentry_cat_modifier), _("autres"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MA_comboboxentry_cat_modifier), "");

  MA_label_cat_modifier = gtk_label_new (_("Cat\303\251gorie"));
  gtk_widget_show (MA_label_cat_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_label_cat_modifier, 520, 416);
  gtk_widget_set_size_request (MA_label_cat_modifier, 120, 25);

  MA_button_acceuil_modifier = gtk_button_new ();
  gtk_widget_show (MA_button_acceuil_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_button_acceuil_modifier, 392, 680);
  gtk_widget_set_size_request (MA_button_acceuil_modifier, 296, 93);

  MA_alignment_acceuil_modifier = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (MA_alignment_acceuil_modifier);
  gtk_container_add (GTK_CONTAINER (MA_button_acceuil_modifier), MA_alignment_acceuil_modifier);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (MA_alignment_acceuil_modifier), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox14), label60, FALSE, FALSE, 0);

  MA_button_modifier_modifier = gtk_button_new ();
  gtk_widget_show (MA_button_modifier_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_button_modifier_modifier, 1080, 680);
  gtk_widget_set_size_request (MA_button_modifier_modifier, 296, 93);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (MA_button_modifier_modifier), alignment19);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox15), label61, FALSE, FALSE, 0);

  MA_entry_refm_modifier = gtk_entry_new ();
  gtk_widget_show (MA_entry_refm_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_entry_refm_modifier, 208, 72);
  gtk_widget_set_size_request (MA_entry_refm_modifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MA_entry_refm_modifier), 8226);

  MA_label_refm_modifier = gtk_label_new (_("R\303\251f \303\240 modifier"));
  gtk_widget_show (MA_label_refm_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_label_refm_modifier, 24, 72);
  gtk_widget_set_size_request (MA_label_refm_modifier, 104, 24);

  MA_spinbutton_dpj_modifier_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  MA_spinbutton_dpj_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (MA_spinbutton_dpj_modifier_adj), 1, 0);
  gtk_widget_show (MA_spinbutton_dpj_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_spinbutton_dpj_modifier, 864, 248);
  gtk_widget_set_size_request (MA_spinbutton_dpj_modifier, 60, 27);

  MA_spinbutton_dpm_modifier_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  MA_spinbutton_dpm_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (MA_spinbutton_dpm_modifier_adj), 1, 0);
  gtk_widget_show (MA_spinbutton_dpm_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_spinbutton_dpm_modifier, 1000, 248);
  gtk_widget_set_size_request (MA_spinbutton_dpm_modifier, 60, 27);

  MA_spinbutton_dpa_modifier_adj = gtk_adjustment_new (1, 2021, 2031, 1, 10, 10);
  MA_spinbutton_dpa_modifier = gtk_spin_button_new (GTK_ADJUSTMENT (MA_spinbutton_dpa_modifier_adj), 1, 0);
  gtk_widget_show (MA_spinbutton_dpa_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_spinbutton_dpa_modifier, 1120, 248);
  gtk_widget_set_size_request (MA_spinbutton_dpa_modifier, 60, 27);

  MA_label_stockage_modifier = gtk_label_new (_("Stockage"));
  gtk_widget_show (MA_label_stockage_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_label_stockage_modifier, 520, 504);
  gtk_widget_set_size_request (MA_label_stockage_modifier, 120, 25);

  MA_radiobutton_congele_modifier = gtk_radio_button_new_with_mnemonic (NULL, _("Congel\303\251"));
  gtk_widget_show (MA_radiobutton_congele_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_radiobutton_congele_modifier, 864, 504);
  gtk_widget_set_size_request (MA_radiobutton_congele_modifier, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (MA_radiobutton_congele_modifier), MA_radiobutton_congele_modifier_group);
  MA_radiobutton_congele_modifier_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (MA_radiobutton_congele_modifier));

  MA_radiobutton_refrigere_modifier = gtk_radio_button_new_with_mnemonic (NULL, _("R\303\251frig\303\251r\303\251"));
  gtk_widget_show (MA_radiobutton_refrigere_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_radiobutton_refrigere_modifier, 1032, 504);
  gtk_widget_set_size_request (MA_radiobutton_refrigere_modifier, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (MA_radiobutton_refrigere_modifier), MA_radiobutton_congele_modifier_group);
  MA_radiobutton_congele_modifier_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (MA_radiobutton_refrigere_modifier));

  MA_radiobutton_TA_modifier = gtk_radio_button_new_with_mnemonic (NULL, _("Temperature ambiante"));
  gtk_widget_show (MA_radiobutton_TA_modifier);
  gtk_fixed_put (GTK_FIXED (MA_fixed5), MA_radiobutton_TA_modifier, 1208, 504);
  gtk_widget_set_size_request (MA_radiobutton_TA_modifier, 192, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (MA_radiobutton_TA_modifier), MA_radiobutton_congele_modifier_group);
  MA_radiobutton_congele_modifier_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (MA_radiobutton_TA_modifier));

  g_signal_connect ((gpointer) MA_button_acceuil_modifier, "clicked",
                    G_CALLBACK (on_MA_button_acceuil_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_button_modifier_modifier, "clicked",
                    G_CALLBACK (on_MA_button_modifier_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_radiobutton_congele_modifier, "toggled",
                    G_CALLBACK (on_MA_radiobutton_congele_modifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) MA_radiobutton_refrigere_modifier, "toggled",
                    G_CALLBACK (on_MA_radiobutton_refrigere_modifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) MA_radiobutton_TA_modifier, "toggled",
                    G_CALLBACK (on_MA_radiobutton_TA_modifier_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MA_interface_modifier, MA_interface_modifier, "MA_interface_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_fixed5, "MA_fixed5");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_entry_nom_modifier, "MA_entry_nom_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_label_nom_modifier, "MA_label_nom_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_entry_ref_modifier, "MA_entry_ref_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_label_dp_modifier, "MA_label_dp_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_label_dpj_modifier, "MA_label_dpj_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_label_dpm_modifier, "MA_label_dpm_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_label_dpa_modifier, "MA_label_dpa_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_entry_qte_modifier, "MA_entry_qte_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_label_qte_modifier, "MA_label_qte_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_label_ref_modifier, "MA_label_ref_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_alignment_cat_modifier, "MA_alignment_cat_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_comboboxentry_cat_modifier, "MA_comboboxentry_cat_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_label_cat_modifier, "MA_label_cat_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_button_acceuil_modifier, "MA_button_acceuil_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_alignment_acceuil_modifier, "MA_alignment_acceuil_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, image14, "image14");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, label60, "label60");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_button_modifier_modifier, "MA_button_modifier_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, image15, "image15");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, label61, "label61");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_entry_refm_modifier, "MA_entry_refm_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_label_refm_modifier, "MA_label_refm_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_spinbutton_dpj_modifier, "MA_spinbutton_dpj_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_spinbutton_dpm_modifier, "MA_spinbutton_dpm_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_spinbutton_dpa_modifier, "MA_spinbutton_dpa_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_label_stockage_modifier, "MA_label_stockage_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_radiobutton_congele_modifier, "MA_radiobutton_congele_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_radiobutton_refrigere_modifier, "MA_radiobutton_refrigere_modifier");
  GLADE_HOOKUP_OBJECT (MA_interface_modifier, MA_radiobutton_TA_modifier, "MA_radiobutton_TA_modifier");

  return MA_interface_modifier;
}

GtkWidget*
create_MA_Interface_Rupture (void)
{
  GtkWidget *MA_Interface_Rupture;
  GtkWidget *MA_fixed6;
  GtkWidget *MA_treeview_LR_rupture;
  GtkWidget *MA_button_actualiser_rupture;
  GtkWidget *alignment22;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label68;
  GtkWidget *MA_button_acceuil_rupture;
  GtkWidget *alignment23;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label69;

  MA_Interface_Rupture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MA_Interface_Rupture), _("Rupture de Stock"));

  MA_fixed6 = gtk_fixed_new ();
  gtk_widget_show (MA_fixed6);
  gtk_container_add (GTK_CONTAINER (MA_Interface_Rupture), MA_fixed6);

  MA_treeview_LR_rupture = gtk_tree_view_new ();
  gtk_widget_show (MA_treeview_LR_rupture);
  gtk_fixed_put (GTK_FIXED (MA_fixed6), MA_treeview_LR_rupture, 304, 160);
  gtk_widget_set_size_request (MA_treeview_LR_rupture, 552, 304);

  MA_button_actualiser_rupture = gtk_button_new ();
  gtk_widget_show (MA_button_actualiser_rupture);
  gtk_fixed_put (GTK_FIXED (MA_fixed6), MA_button_actualiser_rupture, 752, 480);
  gtk_widget_set_size_request (MA_button_actualiser_rupture, 104, 29);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (MA_button_actualiser_rupture), alignment22);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox18), label68, FALSE, FALSE, 0);

  MA_button_acceuil_rupture = gtk_button_new ();
  gtk_widget_show (MA_button_acceuil_rupture);
  gtk_fixed_put (GTK_FIXED (MA_fixed6), MA_button_acceuil_rupture, 168, 512);
  gtk_widget_set_size_request (MA_button_acceuil_rupture, 200, 53);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (MA_button_acceuil_rupture), alignment23);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox19), label69, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) MA_treeview_LR_rupture, "row_activated",
                    G_CALLBACK (on_MA_treeview_LR_rupture_row_activated),
                    NULL);
  g_signal_connect ((gpointer) MA_button_actualiser_rupture, "clicked",
                    G_CALLBACK (on_MA_button_actualiser_rupture_clicked),
                    NULL);
  g_signal_connect ((gpointer) MA_button_acceuil_rupture, "clicked",
                    G_CALLBACK (on_MA_button_acceuil_rupture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MA_Interface_Rupture, MA_Interface_Rupture, "MA_Interface_Rupture");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, MA_fixed6, "MA_fixed6");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, MA_treeview_LR_rupture, "MA_treeview_LR_rupture");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, MA_button_actualiser_rupture, "MA_button_actualiser_rupture");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, image18, "image18");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, label68, "label68");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, MA_button_acceuil_rupture, "MA_button_acceuil_rupture");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, image19, "image19");
  GLADE_HOOKUP_OBJECT (MA_Interface_Rupture, label69, "label69");

  return MA_Interface_Rupture;
}

