/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MA_Interface_Acceuil (void);
GtkWidget* create_MA_Interface_Ajouter (void);
GtkWidget* create_MA_Interface_Supprimer (void);
GtkWidget* create_MA_Interface_Rechercher (void);
GtkWidget* create_MA_interface_modifier (void);
GtkWidget* create_MA_Interface_Rupture (void);
