/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_az_inscription (void);
GtkWidget* create_az_connexion (void);
GtkWidget* create_az_admin (void);
GtkWidget* create_adminajout (void);
GtkWidget* create_az_supression (void);
GtkWidget* create_az_modif (void);
GtkWidget* create_ad_modif (void);
GtkWidget* create_adminaffiche (void);
GtkWidget* create_affichage_niveau (void);
GtkWidget* create_affiche (void);
GtkWidget* create_Ajout (void);
GtkWidget* create_suppression (void);
GtkWidget* create_modification (void);
GtkWidget* create_cptdef (void);
GtkWidget* create_MA_Interface_Acceuil (void);
GtkWidget* create_MA_Interface_Ajouter (void);
GtkWidget* create_MA_Interface_Supprimer (void);
GtkWidget* create_MA_Interface_Rechercher (void);
GtkWidget* create_MA_interface_modifier (void);
GtkWidget* create_MA_Interface_Rupture (void);
